project:
  type: website

website:
  title: "Lauritz van Luijk"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: talks.qmd
        text: Talks
      - href: teaching.qmd
        text: Teaching


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true

include-in-header:
  text: |
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">